version: "2.4"

services:
  taskmanagement_db:
    image: postgres:13.1
    container_name: taskmanagement_db
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_PORT: ${DB_PORT}
    healthcheck:
      test: pg_isready -U ${DB_USERNAME} -h ${DB_HOST}
    ports:
      - ${DB_PORT}:${DB_PORT}
    networks:
      - proxy
      - internal
    volumes:
      - pgdata-dev:/var/lib/postgresql/data
  taskmanagement_api:
    image: taskmanagement:dev
    container_name: taskmanagement_api
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    depends_on:
      taskmanagement_db:
        condition: service_healthy
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - ".:/var/www/taskmanagement_api"
    environment:
      NODE_ENV: development
      DB_HOST: taskmanagement_db
      DB_NAME: ${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      JWT_SECRET: ${JWT_SECRET}
    networks:
      - proxy
      - internal
      
volumes:
  pgdata-dev:

networks:
  proxy:
  internal:
